### ISSUE TITLE
[Discussion] New name

### ISSUE THREAD

**Issue by KodySalak** [gregtwallace/certwarden#48]
Your recent release said you were looking to rename Certhub. 

I was wanting a place to spitball ideas, so I made this!

SSLMan
SSLCentral
CertMan (I saw this in the thread and it looks like digicert already has something named after that, so I wouldn't).

**Comment by radziejewicz** [comment]
SSLMan has my vote :)

**Comment by gregtwallace** [comment]
Got a number of other suggestions else where as well. Decided on Cert Warden and working on the rebranding now.
