### ISSUE TITLE
Upgraded, now get app/app_create.go:178	failed to configure https cert: no such record found in storage

### ISSUE THREAD

**Issue by parallax-home** [gregtwallace/certwarden#50]
Running the latest Docker image, 0.21.2

I have been using the app since your first posting on Reddit, and all went well until the change to Certwarden and the server default certificate name from legocerthub to serverdefault. With that my front ends could no longer retrieve their certs, and this turned out to be because Certwarden wasn't running on the HTTPS port any more.

Looking at the logs it updated the name of the cert as part of the upgrade process, but since then I get the error : 
`app/app_create.go:178	failed to configure https cert: no such record found in storage`

and thus
```
2024-05-15T22:44:28.590Z	info	app/router_make.go:161	frontend hosting enabled and available at: /certwarden/app
2024-05-15T22:44:28.590Z	warn	app/run.go:185	failed to configure https; will run over insecure http
2024-05-15T22:44:28.590Z	info	app/run.go:186	starting insecure http server bound to :4050
```
I tried manually changing the name of the default cert to serverdefault again, then I deleted the whole cert and made a new one called serverdefault, same problem.

So then I wrote a new stack from scratch, deleted the app data directory, redeployed the Docker image, started a brand new installation, and created the serverdefault cert successfully. I restart Certwarden and then get the same error above, so I can never get to HTTPS mode.

Um, help?

**Comment by gregtwallace** [comment]
That’s a really strange one. I’ll do some testing and see if I can recreate.

**Comment by gregtwallace** [comment]
When I originally wrote the code I planned to name the new cert "certwarden". I changed my mind and updated everything except the default cert name. 

Oops.

Apparently everyone else is using a non-default name or reverse proxty or something. Next release will be fixed.
