### ISSUE TITLE
Install script errors

### ISSUE THREAD

**Issue by VendettaMike** [gregtwallace/certwarden#51]
I'm performing a fresh direct install on Rocky Linux and a few errors exist in the install.sh script. 

Install.sh fails at line 19
```
# copy all files to install path
mkdir "$path"
cp -R ../* "$install_path"
```
_mkdir_ should be creating _$install_path_ instead of _path_

In addition, Install.sh fails at line 29
```
# install and start service
cp ./certwarden.service /etc/systemd/system/certwarden.service
systemctl daemon-reload
```

_certwarden.service_ doesn't exist as _legocerthub.service_ is still distributed. Need to do a quick rename! 

After that, the install succeeds.

**Comment by gregtwallace** [comment]
Thank you.

Bummer, literally just ran a release a moment ago. Ah well, it'll be in the next one.
