### ISSUE TITLE
Error when modifying Providers

### ISSUE THREAD

**Issue by onyxhat** [gregtwallace/certwarden#53]
I'm running `v0.21.3` in docker behind Traefik via a subdomain within my LAN (e.g. `certs.mydomain.local`). I've been able to generate a private key and ACME account to LetsEncrypt successfully, but when trying to add a provider for `acme.sh` or remove the default provider I'm receiving the following error.

```error
An API error has occurred.
Status Code: 400
Message: error: request validation (param or payload) invalid
```

I've left the config file default and tried adding `cors_permitted_crossorigins` matching my internal DNS and/or port redirection, but get the same error.

**Comment by gregtwallace** [comment]
What does the log say when you try to add? If nothing, interesting set debug log level. 

You won’t be able to delete the existing provider if it’s the only one.

**Comment by user00265** [comment]
I got this error when trying to use an asterisk for the domain but while using the dns-01 Cloudflare provider.

**Comment by gregtwallace** [comment]
You can only have one wildcard provider. Otherwise the app wouldn't know which one to use.
