### ISSUE TITLE
[FEATURE REQUEST] External account binding

### ISSUE THREAD

**Issue by jonathanwalter** [gregtwallace/certwarden#54]
Thank you for a great product!

It would be great to be able to use external account binding ([EAB](https://docs.digicert.com/zf/trust-lifecycle-manager/integration-guides/third-party-acme-integration/acme-external-account-binding--eab-.html)) as a Challenge Provider.

If there already is a way to do it, I can't find the docs for it...

**Comment by gregtwallace** [comment]
Thank you for the compliment. 

EAB is already implemented. However, it’s purpose is not to solve challenges. EAB is used when registering an ACME account. It is only used if the ACME Server requires it. If Cert Warden detects EAB is required it will automatically prompt for and require the additional fields when you attempt the ‘Register’ action in the account.
