### ISSUE TITLE
Add post delete script for certificates

### ISSUE THREAD

**Issue by Buco7854** [gregtwallace/certwarden#57]
Hello,

I use post processing script to write the certificate in a file so that it can be used by my web server.
It's not super important but I wondered if that would be possible to add post delete script so that when i delete the cert in certwarden i can have a script that cleanup the certificate file.

**Comment by gregtwallace** [comment]
Initial setup and tear down events are generally one time occurrences that are done manually. I'm not understanding the utility of an automated delete script in this context.

Can you help me understand a scenario / use case?

**Comment by Buco7854** [comment]
Just so that it's easier to do whatever for cleanup. After post processing you generally "setup" something with the script. So basically if I delete the cert it means whatever I setup need cleanup (in most case).

It's not that bothersome to go and delete the certificate file I created in post processing but it would be nice to have some script automatically called on delete to do it for me.

It's not that important a feature, just a small suggestion.

**Comment by gregtwallace** [comment]
How often are you deleting things?

In my mind I am seeing each renewal overwriting the old files (so deleting old files isn't needed). In that case, you would only ever have to delete once whenever you do the final teardown of whatever you're providing the files to.

If you're serializing the files or something, your post-process script could check for old files and delete them as a final step of the process which installs the new files.

**Comment by Buco7854** [comment]
Well not really often for sure. my setup is fine as is, its probably not worth the time.

**Comment by gregtwallace** [comment]
Ok. This can be readdressed in the future if it becomes a commonly repeated activity for some reason.
