### ISSUE TITLE
http 01 challenge error when facing the internet

### ISSUE THREAD

**Issue by vagus-solus** [gregtwallace/certwarden#58]
hello wallace,

i have installed certwarden on a docker image, configured and working properly, i have a problem is that i have nginx server as reverse proxy, whenever i enable dst nat to forward port 80 and 443 to nginx, certwarden stops and start giving error (error, acme/directory.go:108, directory https://acme-staging-v02.api.letsencrypt.org/directory update failed (Get "https://acme-staging-v02.api.letsencrypt.org/directory": context deadline exceeded (Client.Timeout exceeded while awaiting headers)), will retry again in 5m26.8s)

any help

**Comment by gregtwallace** [comment]
That error suggests whatever you’re doing is causing the container to lose internet connectivity. Exec ping within the container for something like Google.com and you’ll probably see a timeout error.
