### ISSUE TITLE
Cipher types

### ISSUE THREAD

**Issue by clas0415** [gregtwallace/certwarden#60]
Is there a why to restrict the types of cipher that certwarden will respond to?
At the moment it responds to 3DES-CBC, which I'd like to disable.
Could this become an settings option or preference file?
[I may have missed something obvious, my apologies if I have!]

Many thanks!

**Comment by gregtwallace** [comment]
Golang defaults are in place for this type of control. The language deprecates and removes broken ciphers over time. If you want more grandular control than this, I'd recommend sticking Cert Warden behind your proxy of choice and making these tweaks in the proxy settings.
