### ISSUE TITLE
acme.sh support for `--challange-alias` / domain delegation

### ISSUE THREAD

**Issue by matthiasvop** [gregtwallace/certwarden#62]
I've come across certwarden just today - and it seems to fit exactly what i'm looking for.

I'm however wondering how to configure the acme acme.sh provider to work for a manual request like the following 

```
acme.sh --issue --dns dns_cf -d domain.example.com --challenge-alias certs-example.com
```

Obviously this requires additional setup (a CNAME that points from `_acme-challenge.domain.example.com` to `_acme-challenge.certs-example.com`

(the documentation doesn't seem to provide this - and tests show no additional arguments to pass to acme.sh).

## Reasoning: 
t's a security topic regarding the Cloudflare API key, really.

`example.com` is the main domain (an important one) - and I'd like to have the cloudflare token only valid for `certs-example.com`. 
on cloudflare, i can limit only the token to the zone (not subdomain) - so DNS domain delegation to a mostly unimportant secondary domain seems to be the best approach.

**Comment by gregtwallace** [comment]
I see the value here. I'd probably insert some kind of shim between the main app and the challenge providers to allow mapping domains to aliases. This would make the result challenge method agnostic.

I'll have to ponder the best way to do that.

**Comment by fdbailes** [comment]
Hi there, I was looking at this project and looks really good.

I'm having the same problem, we have a primary domain with bind dns server (no api), but I read about DNS alias mode in acme.sh and I have a spare domain I can set up in Cloudflare just for this challenge.

I think this would be easier than using RFC 2136 with split view bind server

Really apreciate if you can modify certwarden to be able to use dns alias mode in acme.sh challenge.

**Comment by gregtwallace** [comment]
This will be in the next release.
