### ISSUE TITLE
Improve error message when configuring `dns-01 go-acme le-go`

### ISSUE THREAD

**Issue by LeGmask** [gregtwallace/certwarden#65]
Hey, 
I've tried to configure the `dns-01 go-acme le-go` provider, but I keep getting an error:
```
An API error has occurred.
Status Code: 400
Message: error: request validation (param or payload) invalid
```

And If I configure it using the config file, it shows an empty `dns_provider_name`. My theory it that a `yaml:"dns_provider_name" is missing here:
https://github.com/gregtwallace/certwarden-backend/blob/1bf9bd2afe87b5b3030d85942555b3259a863b30/pkg/challenges/providers/dns01goacme/service.go#L32

**Comment by gregtwallace** [comment]
Turn on debug logging and it should produce a message that indicates the problem.

**Comment by LeGmask** [comment]
Yes, I've added the missing environment and now it works ! 
```
failed to add new provider (failed to configure go-acme dns provider (rfc2136: some credentials information are missing: RFC2136_NAMESERVER))
```
I edit the issue, the error message can be improved...

**Comment by gregtwallace** [comment]
Closing this in favor of the more general issue I opened.
