### ISSUE TITLE
[FEATURE REQUEST] New certificate via API 

### ISSUE THREAD

**Issue by tompaah** [gregtwallace/certwarden#68]
Would be nice if Cert Warden had the possibility to create new certificates via the API. Preferrably authenticated with the Admin users password as token (either that or associate a proper token with the Admin user).

It could return the call with API keys to the certificate and key generated in the process. This would enable clients to be totally self-sufficient.

**Comment by webprofusion-chrisc** [comment]
Cert orders can take a while (even minutes) to complete via ACME, so you would need to have the API create the certificate configuration, perhaps another to call to start the order, then an endpoint you can poll for the status. 

If making it practical for general use you would create a user for specific apps or services, then associate one or more tokens or keys they can use for calls, that way one service/consumer doesn't know credentials for other certificates it shouldn't be able to access.

**Comment by gregtwallace** [comment]
The backend API already exists, it is just a matter of crafting whatever client you're interested in. I do not intend to support going this route though, as it isn't really the intent of the application. You're certainly welcome to leverage this however you see fit though.

The routes are all listed in: https://github.com/gregtwallace/certwarden-backend/blob/master/pkg/domain/app/router_make.go

All of the API calls are relatively straightforward in the frontend react code, if you want to see which route is being called for any given activity.

e.g., Login:
https://github.com/gregtwallace/certwarden-frontend/blob/07ae73bd8c484a654b8ead0de0ba1d902c58c11c/src/components/Main/Login/Login.tsx#L28
https://github.com/gregtwallace/certwarden-frontend/blob/07ae73bd8c484a654b8ead0de0ba1d902c58c11c/src/components/Main/Login/Login.tsx#L85
