### ISSUE TITLE
Authorization Header not passed after login

### ISSUE THREAD

**Issue by JustinBack** [gregtwallace/certwarden#69]
Currently I am facing the issue where an existing instance and a newly created instance fails to pass the authorization header to the api and I get kicked back instantly to the login screen after logging in.

Login works
![grafik](https://github.com/user-attachments/assets/1a454b6e-b3ad-4538-be32-b510d333e87b)
 
Session token can be retrieved and is saved as a cookie
![grafik](https://github.com/user-attachments/assets/542d685f-f0f3-4793-99d5-2b8d2cdb265f)

Further requests are missing the authorization header
![grafik](https://github.com/user-attachments/assets/99939d96-631b-4b4f-bd8d-8638d073a95d)

and I get kicked to the login screen.

I can confirm it works in postman when I use the session_token to retrieve certificates

Error logs:

```
certwarden  | 2024-12-03T09:51:38.435Z  info    auth/handlers.go:35     client 172.18.0.1:48778: attempting login
certwarden  | 2024-12-03T09:51:38.844Z  info    auth/handlers.go:87     client 172.18.0.1:48778: user 'admin' logged in
certwarden  | 2024-12-03T09:51:38.957Z  debug   auth/validate.go:29     client 172.18.0.1:48778: GET /api/v1/orders/currentvalid?limit=20&offset=0&sort=valid_to.asc failed (access token is missing)
certwarden  | 2024-12-03T09:51:38.957Z  debug   app/middleware_returnval_handling.go:76 client 172.18.0.1:48778: GET /api/v1/orders/currentvalid?limit=20&offset=0&sort=valid_to.asc 468.166µs: served err response
certwarden  | 2024-12-03T09:51:39.005Z  debug   auth/validate.go:29     client 172.18.0.1:48780: GET /api/v1/app/updater/new-version failed (access token is missing)
certwarden  | 2024-12-03T09:51:39.005Z  debug   app/middleware_returnval_handling.go:76 client 172.18.0.1:48780: GET /api/v1/app/updater/new-version 303.597µs: served err response
certwarden  | 2024-12-03T09:51:39.041Z  info    auth/handlers.go:108    client 172.18.0.1:48778: attempting access token refresh
certwarden  | 2024-12-03T09:51:39.042Z  info    auth/handlers.go:146    client 172.18.0.1:48778: access token refresh for user 'admin' succeeded
```

Running version [v0.22.3](https://github.com/gregtwallace/certwarden/releases/tag/v0.22.3)

**Comment by gregtwallace** [comment]
You mention an existing instance. 

Was it previously working on v0.22.2?
Have you tried clearing cookies and/or an incognito window?

There weren't really any changes on this front between the last version and this one.

**Comment by JustinBack** [comment]
Yes it suddenly stopped working, I've tried several browsers in incognito as well as different devices.

I started using certwarden yesterday and those issues appeared today suddenly

**Comment by gregtwallace** [comment]
Did you put it behind a proxy or anything? Which build (container, windows, linux)?

**Comment by JustinBack** [comment]
Yeah its running behind an nginx on docker linux, though the proxy configuration did not change

**Comment by JustinBack** [comment]
Thats the next thing I tried and its the same result

**Comment by gregtwallace** [comment]
Is your session storage getting set? The header is included when the session storage has a token in it.

![image](https://github.com/user-attachments/assets/1ec8f088-e30a-4213-b585-840a8625c81d)

**Comment by JustinBack** [comment]
I've just checked with the DC and the firewall is not filtering any Headers, I suspected this was the cause.



> Is your session storage getting set? The header is included when the session storage has a token in it.
> 
> ![image](https://private-user-images.githubusercontent.com/63136063/392179532-1ec8f088-e30a-4213-b585-840a8625c81d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODc3MjYsIm5iZiI6MTczMzk4NzQyNiwicGF0aCI6Ii82MzEzNjA2My8zOTIxNzk1MzItMWVjOGYwODgtZTMwYS00MjEzLWI1ODUtODQwYTg2MjVjODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA3MTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MjA4YjdkMTQ0MzhmMzg1NzI4Y2ZkOWQ1YTFmZDNlNGM5ZDVkZTUyMTFiYjQyYmNjZDg0YzViYmQ5NjkyNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xdzqKeeAlKHJBb2Vm531i4-BCJ0VgB64IIozr-GzHZ0)

Nope, thats not happening. The only item in the local storage is theme_dark_mode, session storage is empty.


I've tried with multiple devices and browsers. No luck so far

**Comment by JustinBack** [comment]
After further debugging I have found the issue, the time of the host was off by an hour and a half, apparently the NTP Server was not reachable.


The log did not show any message that the access token expired thats why I never suspected it could be a date difference. Maybe add some logging in the UI/Console that the access token expired?

**Comment by gregtwallace** [comment]
Don't think I would have ever guess that as the issue. I added checking / error message for it.
